# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FilePathField(match='*.ssim')),
                ('orig_file', models.FilePathField(match='*.ssim')),
                ('tmp_file', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pid', models.PositiveSmallIntegerField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='django_stsim.Library')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_result', models.BooleanField(default=False)),
                ('sid', models.PositiveSmallIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='django_stsim.Project')),
            ],
        ),
        migrations.CreateModel(
            name='StateClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateclass_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('development', models.CharField(max_length=100)),
                ('structure', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stateclasses', to='django_stsim.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Stratum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stratum_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strata', to='django_stsim.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(default=0.0)),
                ('age_reset', models.CharField(default='No', max_length=3)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_stsim.Scenario')),
                ('stateclass_dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stateclass_dest', to='django_stsim.StateClass')),
                ('stateclass_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stateclass_src', to='django_stsim.StateClass')),
                ('stratum_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stratum_dest', to='django_stsim.Stratum')),
                ('stratum_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stratum_src', to='django_stsim.Stratum')),
            ],
        ),
        migrations.CreateModel(
            name='TransitionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_groups', to='django_stsim.Project')),
            ],
        ),
        migrations.CreateModel(
            name='TransitionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_type_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_types', to='django_stsim.Project')),
            ],
        ),
        migrations.CreateModel(
            name='TransitionTypeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.CharField(default='', max_length=3)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_type_groups', to='django_stsim.Project')),
                ('transition_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_stsim.TransitionGroup')),
                ('transition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_stsim.TransitionType')),
            ],
        ),
        migrations.AddField(
            model_name='transitiongroup',
            name='transition_types',
            field=models.ManyToManyField(to='django_stsim.TransitionType'),
        ),
        migrations.AddField(
            model_name='transition',
            name='transition_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_stsim.TransitionType'),
        ),
    ]
